import type { Metadata } from "next";
import { Inter, Raleway } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/navbar";
import Footer from "@/components/footer/footer";
import { UserProvider } from "@auth0/nextjs-auth0/client";


const inter = Inter({ subsets: ["latin"] });
const raleway = Raleway({ subsets: ["latin"], weight: ["500", "200"] });

export const metadata: Metadata = {
  title: "EduFree",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <UserProvider>
        <body className={`${raleway.className} ${inter.className}`}>
          <Navbar />
          {children}
          <Footer />
        </body>
      </UserProvider>
    </html>
  );
}
